[project]
name = "ml-end-to-end"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
